FROM ubuntu:18.04

VOLUME /src
WORKDIR /src

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y \
        gcc-7=7.3.0-3ubuntu1 \
        g++-7=7.3.0-3ubuntu1 \
        cmake \ 
        libboost1.65-all-dev \
        libgtest-dev \
 && apt-get clean autoclean \
 && apt-get autoremove -y

RUN cd /usr/src/gtest \
 && cmake CMakeLists.txt \
 && make \
 && cp *.a /usr/lib
